### ISSUE TITLE
Please enter a correct entity model.

### ISSUE THREAD

**Issue by NeonForgeGames** [magento-hackathon/FastSimpleExport2#1]
Hi,

I installed the magneto 2.1.0 and the only active modules except the default ones are "FastSimpleExport", "FastSimpleImport" and "FastSimpleImportDemo". The import Demo works just fine, but when I want to test the order export part of the demo I get the Error mentioned in the headline. "Please enter a correct entity model." Any Ideas how I can fix it? 
That's the output of the commandline following the command: bin/magento fastsimpleimportdemo:orders:export

`Export started
Please enter a correct entity model.
array(0) {
}
Export finished. Elapsed time: 0.91s
`

Any hints pointing me in the right direction would be greatly appreciated.
Cheers

**Comment by NeonForgeSoftware** [comment]
Forgott to post the stack trace of exception.log
`[2016-10-10 12:52:10] main.CRITICAL: Magento\Framework\Exception\LocalizedException: Invalid entity_type specified: sales_order in /var/www/html/magento2016/vendor/magento/module-eav/Model/Config.php:354
Stack trace:
#0 /var/www/html/magento2016/vendor/magento/module-import-export/Model/Export/Entity/AbstractEav.php(72): Magento\Eav\Model\Config->getEntityType('sales_order')
#1 /var/www/html/magento2016/app/code/FireGento/FastSimpleExport/Model/Export/Order.php(104): Magento\ImportExport\Model\Export\Entity\AbstractEav->__construct(Object(Magento\Framework\App\Config), Object(Magento\Store\Model\StoreManager), Object(Magento\ImportExport\Model\Export\Factory), Object(Magento\ImportExport\Model\ResourceModel\CollectionByPagesIteratorFactory), Object(Magento\Framework\Stdlib\DateTime\Timezone), Object(Magento\Eav\Model\Config), Array)
#2 /var/www/html/magento2016/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(93): FireGento\FastSimpleExport\Model\Export\Order->__construct(Object(Magento\Framework\App\Config), Object(Magento\Store\Model\StoreManager), Object(Magento\ImportExport\Model\Export\Factory), Object(Magento\ImportExport\Model\ResourceModel\CollectionByPagesIteratorFactory), Object(Magento\Framework\Stdlib\DateTime\Timezone), Object(Magento\Eav\Model\Config), Object(Magento\Sales\Model\ResourceModel\Order\CollectionFactory), Array)
#3 /var/www/html/magento2016/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(89): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('FireGento\\FastS...', Array)
#4 /var/www/html/magento2016/vendor/magento/framework/ObjectManager/ObjectManager.php(57): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('FireGento\\FastS...', Array)
#5 /var/www/html/magento2016/vendor/magento/module-import-export/Model/Export/Entity/Factory.php(42): Magento\Framework\ObjectManager\ObjectManager->create('FireGento\\FastS...')
#6 /var/www/html/magento2016/vendor/magento/module-import-export/Model/Export.php(99): Magento\ImportExport\Model\Export\Entity\Factory->create('FireGento\\FastS...')
#7 /var/www/html/magento2016/vendor/magento/module-import-export/Model/Export.php(177): Magento\ImportExport\Model\Export->_getEntityAdapter()
#8 /var/www/html/magento2016/app/code/FireGento/FastSimpleExport/Model/Exporter.php(54): Magento\ImportExport\Model\Export->export()
#9 /var/www/html/magento2016/app/code/FireGento/FastSimpleImportDemo/Console/Command/AbstractExportCommand.php(94): FireGento\FastSimpleExport\Model\Exporter->export()
#10 /var/www/html/magento2016/vendor/symfony/console/Symfony/Component/Console/Command/Command.php(257): FireGento\FastSimpleImportDemo\Console\Command\AbstractExportCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /var/www/html/magento2016/vendor/symfony/console/Symfony/Component/Console/Application.php(874): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /var/www/html/magento2016/vendor/symfony/console/Symfony/Component/Console/Application.php(195): Symfony\Component\Console\Application->doRunCommand(Object(FireGento\FastSimpleImportDemo\Console\Command\Orders\ExportOrders), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /var/www/html/magento2016/vendor/magento/framework/Console/Cli.php(96): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /var/www/html/magento2016/vendor/symfony/console/Symfony/Component/Console/Application.php(126): Magento\Framework\Console\Cli->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /var/www/html/magento2016/bin/magento(23): Symfony\Component\Console\Application->run()
#16 {main} [] []`

**Comment by EliasKotlyar** [comment]
Hello Crashmt,

there was a bug in this Version. I have corrected it. Please upgrade Firegento FastSimpleDemo & FastSimpleExport to the newest Version of the master-branch using composer. Now the export of Orders should work out of the Box.

Greetings
Elias
